### ISSUE TITLE
Create a build script which generates a lib folder with all the scripts files transpiled.

### ISSUE THREAD

**Issue by imbhargav5** [cbanning510/web-scaffold#1]
The lib folder should be on the same level as src. In other words, lib should be src's sibling. 
The build script shouldn't just transpile index.js , it should transpile the whole src folder and create a lib folder out of it. 

Which means use `--out-dir` instead of `--out-file`.

Now, read about npm pre and post scripts from [here](https://docs.npmjs.com/misc/scripts).

Figure out a way to remove previously generated lib folder whenever you run a fresh `npm run build`.

**Comment by imbhargav5** [comment]
Please create a pull request here. And I will merge it. You will need to create a new branch, make changes, push the branch to github and link this issue to it.

**Comment by cbanning510** [comment]
Great. You managed to create a PR.
Actually , there are a couple of things more to do.

Add lib to .gitignore
Remove transpiled files from src
In the start script, remove cd server, instead do, nodemon src/server (index.js is the default file which will be run)

**Comment by cbanning510** [comment]
Okay, I pushed the changes

**Comment by imbhargav5** [comment]
#3
