### ISSUE TITLE
create 3 routes/views: welcome page, employee list, add employee form

### ISSUE THREAD

**Issue by cbanning510** [cbanning510/web-scaffold#10]
Notes/Homework:
- We won't jump to react right away. We will understand pug first.
- We will use pug templates to render html to the screen.
- Give a quick reading for views and view engines in express. That should help you get started.

Assignment:
1-  create an index route that renders some welcome to the app html. then
2- create a list route that shows all the employees in the database. then
3- create an /addemployee route which shows a form and adds an employee based on the form data

Other notes:
- create a new branch for each feature:
- If you are fixing an issue, create a branch like this fix/{issue_id} (rather than working in the same libDir branch)(you will find issue_id in the url of the issue.
- create branch from master each time you start working on a new issue.
- It's alright if you work on multiple issues at different times, and sometimes some branches are ahead. We don't need to keep merging one on to the other. All branches just get merged onto the master when the issue is solved.

**Comment by cbanning510** [comment]
completed the assignment!! Not sure what to do about the pull requests? I opened a different branch for each feature/route as instructed.

**Comment by imbhargav5** [comment]
So basically you can take a branch and create a pull request from it. Using "New pull request" button in the repository page. I did it for now. But that's generally how it should be done. Easier to keep track of problem and solution attempts.
