### ISSUE TITLE
Add nodemon to the project

### ISSUE THREAD

**Issue by imbhargav5** [cbanning510/web-scaffold#2]

**Comment by cbanning510** [comment]
added nodemon and tested successsfully

**Comment by imbhargav5** [comment]
Great. You managed to create a PR. 
Actually , there are a couple of things more to do. 
 - Add lib to .gitignore
 - Remove transpiled files from src
 - In the start script, remove cd server, instead do, nodemon src/server (index.js is the default file which will be run)

**Comment by cbanning510** [comment]
I don't have any transpiled files in src - maybe my directory structure is incorrect? I just had a test file in there.

**Comment by imbhargav5** [comment]
Oops looks like I commented in the wrong issue. Let's move to that thread.
